#!/usr/bin/env bash

# Version 1.1.0

VALET_REGISTRY=${VALET_REGISTRY:="ghcr.io"}
VALET_IMAGE=${VALET_IMAGE:-"$VALET_REGISTRY/valet-customers/valet-cli"}

docker login $VALET_REGISTRY

docker pull $VALET_IMAGE:latest
